
# 查看具体cpu型号
# rustc --target=x86_64-unknown-linux-gnu --print target-cpus  // currently cascadelake
# [target.x86_64-unknown-linux-gnu]
# [target.x86_64-apple-darwin]
# [target.aarch64-apple-darwin]
rustflags = ["-Ctarget-cpu=native","-Ctarget-feature=+avx2,+sse4.2"]

[build]
incremental = false


[source.crates-io]
replace-with = 'rsproxy'

[source.rsproxy]
registry = "https://rsproxy.cn/crates.io-index"

[registries.rsproxy]
index = "https://rsproxy.cn/crates.io-index"

[net]
git-fetch-with-cli = true

